spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Arquitectura-de-Software-02-2023/server-config
  application:
    name: ms-laboratorio
  
encrypt:
  key: 123456789abcd

server:
  port: 8719 

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8705/eureka/
